version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./src:/app
      - ./data:/data
      - .:/workspace
    environment:
      - BLACK_CACHE_DIR=/workspace/.black-cache
    ports:
      - 5678:5678
    command: ["python", "-m", "debugpy", "--wait-for-client", "--listen", "0.0.0.0:5678", "main.py"]
