[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
/(
    \.git
  | \.venv
  | \.pytest_cache
  | _build
  | buck-out
  | build
  | dist
)/
)
'''
