[tool.black]
line-length = 100
target-version = ['py39']
include = '\.pyi?$'
exclude = '''
(
/(
    \..+
  | _build
  | buck-out
  | build
  | dist
)/
)
'''

[tool.isort]
profile = "black"
line_length = 100 # Not imported from Black profile
